# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: gcc

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[no-ci\]/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH =~ /^feature/
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - test

before_script:
  - apt update && apt -y install make autoconf
  - make env

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - "var/build/*.hex"
  cache:
    paths:
      - var/

lint:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature/
      when: manual
      allow_failure: true
    - when: always
  script:
    - make lint

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
